### PR TITLE
Add additional built-in mail file type detection signature

### PR DESCRIPTION
**Pull request by net1**
Add Key X-*:  for detect mail file

### CODE REVIEW

**Comment by micahsnyder** [comment]
Thanks for the PR @net1. We're all just going on break here.  I'll try to pass this off to our threat research team to assist with review in early January, after the break.  

If they like the change, then the same signanture will needed to be added to `daily.cvd`'s `daily.ftm` file.  And that could make this change take effect immediately, for all versions.

**Comment by Sanesecurity** [comment]
Just in case this is helpful.. a quick look at X- headers.... 

X-0/c.aspx )
X-1/c.aspx" style=3D"word-wrap
X-250ok-CID
X-35BMId
X-Abuse
X-Abuse-Info
X-AbuseCollector
X-Account-ID
X-Accounttype
X-Alimail-AntiSpam
X-AntiAbuse
X-Apparently-To
X-ASID
X-Attachment-Id
X-Authenticated-Id
X-Authenticated-Sender
X-AuthUser
X-Auto-Response-Suppress
X-BatchId
X-Binding
X-BizManager-Bounce-ID
X-Bordeaux-Action-libantispam.so
X-Bordeaux-Action-libclamav.so
X-Bordeaux-Action-libsmtpext.so
X-Bordeaux-Action-libspamsa.so
X-Bordeaux-Detail
X-Bordeaux-LOG
X-Bordeaux-Score
X-Bordeaux-Type
X-BOT-Check
X-Bounce-Path
X-BPS1
X-BQId
X-Brand
X-Campaign
X-Campaign-Activity-ID
X-Campaign-ID
X-Campaign-Uid
X-campaignid
X-CampaignID
X-Channel-ID
X-cid
X-Clab-Family
X-ClientProxiedBy
X-CLOSEIO-EMAIL-ID
X-CM-Analysis
X-CM-Envelope
X-CM-HeaderCharset
X-CM-SenderInfo
X-CM-TRANSID
X-CMAE-Envelope
X-CMID
X-Company_ID
X-Complaints-To
X-Coremail-Antispam
X-Coremail-Locale
X-Cronus-Message-ID
X-Cronus-Original-Message-ID
X-Csa-Complaints
X-CSA-Complaints
X-CTCT-ID
X-CTS-Enabled
X-Customer-Gid
X-Customer-Uid
X-Date
X-Delivery
X-Delivery-Sid
X-Dgwz-Campaign-Uid
X-Dgwz-Customer-Gid
X-Dgwz-Customer-Uid
X-Dgwz-Delivery-Sid
X-Dgwz-EBS
X-Dgwz-Mailer
X-Dgwz-Subscriber-Uid
X-Dgwz-Tracking-Did
X-dmid
X-Domain
X-eBay-MailTracker
X-EBS
X-ei
X-elqPod
X-elqSiteID
X-Email-ID
X-Email-Type
X-EMarSys-Environment
X-EMarSys-Identify
X-EMS-Sign
X-Entity-ID
X-Entity-Ref-ID
X-EOPAttributedMessage
X-EOPTenantAttributedMessage
X-eshot
X-EVCampaignID
X-ExclaimerHostedSignatures-MessageProcessed
X-ExclaimerImprintAction
X-ExclaimerImprintLatency
X-ExclaimerProxyLatency
X-F24-CampaignId
X-Failed-Recipients
X-FBL
X-Feedback-ID
X-Feedback-Identifier
X-Footer
X-Forefront-Antispam-Report
X-Forefront-Antispam-Report-Untrusted
X-Fxyn-Campaign-Uid
X-Fxyn-Customer-Gid
X-Fxyn-Customer-Uid
X-Fxyn-Delivery-Sid
X-Fxyn-EBS
X-Fxyn-Mailer
X-Fxyn-Subscriber-Uid
X-Fxyn-Tracking-Did
X-Get-Message-Sender-Via
X-Gm-Message-State
X-Google-DKIM-Signature
X-Google-Original-Date
X-Google-Sender-Auth
X-Google-Smtp-Source
X-GRID-QID
X-GRID-REF
X-Groups
X-GUID
X-Ham-Report
X-Has-Attach
X-HostingPlatform-Authenticated
X-HostingPlatform-Domain
X-HostingPlatform-Score
X-HostingPlatform-SenderIP
X-HS-Cid
X-IDTechEx-c
X-IDTechEx-et
X-IDTechEx-sp
X-IncomingHeaderCount
X-IncomingTopHeaderMarker
X-inf-BlockName
X-Inf-Campaign
X-inf-dkimDomain
X-inf-dkimSelector
X-Inf-Email-Age
X-inf-iflags
X-inf-package
X-inf-reapedTime
X-inf-scheduledTime
X-Inf-SourceType
X-Inf-Src
X-inf-uflags
X-InfApp
X-InfContact
X-infEng
X-InfSent
X-Intloopheader
X-IP-ID
X-IPAS-Result
X-IronPort-Anti-Spam-Filtered
X-IronPort-AV
X-JID
X-job
X-Job
X-Keap-Emails-Api
X-Kmail-Account
X-Kmail-Message
X-Kmail-Ops
X-Kmail-Relay
X-Letter
X-Library
X-LinkedIn-Class
X-LinkedIn-fbl
X-LinkedIn-Id
X-LinkedIn-Template
X-List
X-ListMember
X-Local-IP
X-Lyrical-Eight
X-MA-Instance
X-MA-Reference
X-MAIL-ID
X-Mail-IP
X-mail_abuse_inquiries
X-MailChannels-Auth-Id
X-MailChannels-SenderId
X-mailer
X-Mailer
X-Mailer-Camp
X-Mailer-Client
X-Mailer-Info
X-Mailer-Info-Extra
X-Mailer-LID
X-Mailer-Recp
X-Mailer-RecptId
X-Mailer-Sent-By
X-Mailer-SID
X-Mailfrom
X-Mailgun-Dkim
X-Mailgun-Sending-Ip
X-Mailgun-Sid
X-Mailgun-Tag
X-Mailgun-Track
X-Mailgun-Track-Clicks
X-Mailgun-Track-Opens
X-Mailgun-Variables
X-MailId
X-Mailin-Campaign
X-Mailin-Client
X-Mailin-EID
X-MailingID
X-Mailru-Msgtype
X-MailScanner-From
X-MailSentId
X-MailSessionID
X-Mailster
X-Mailster-Campaign
X-Mailster-ID
X-MarketoID
X-Mb
X-MC-Ingress-Time
X-MC-Loop-Signature
X-MC-Metadata
X-MC-Relay
X-MC-Unique
X-MC-User
X-Member-ID
X-Memberid
X-Message-Delivery
X-Message-Flag
X-Message-ID
X-Message-Info
X-Message-UUID
X-MessageID
X-messageuid
X-Microsoft-Antispam
X-Microsoft-Antispam-Mailbox-Delivery
X-Microsoft-Antispam-Message-Info
X-Microsoft-Antispam-Message-Info-Original
X-Microsoft-Antispam-PRVS
X-Microsoft-Antispam-Untrusted
X-Microsoft-Original-Message-ID
X-Mimecast-Originator
X-Mimecast-Spam-Score
X-MimeOLE
X-Mimiaid
X-MJ-Mid
X-MJ-SMTPGUID
X-MktArchive
X-MktMailDKIM
X-MS-Dynamics-CodePackageVersion
X-MS-Dynamics-Instance
X-MS-Dynamics-Message-ID
X-MS-Exchange-AntiSpam-MessageData-0
X-MS-Exchange-AntiSpam-MessageData-ChunkCount
X-MS-Exchange-AntiSpam-Relay
X-MS-Exchange-Authentication-Results
X-MS-Exchange-CrossTenant-AuthAs
X-MS-Exchange-CrossTenant-AuthSource
X-MS-Exchange-CrossTenant-fromentityheader
X-MS-Exchange-CrossTenant-FromEntityHeader
X-MS-Exchange-CrossTenant-id
X-MS-Exchange-CrossTenant-Id
X-MS-Exchange-CrossTenant-mailboxtype
X-MS-Exchange-CrossTenant-MailboxType
X-MS-Exchange-CrossTenant-Network-Message-Id
X-MS-Exchange-CrossTenant-originalarrivaltime
X-MS-Exchange-CrossTenant-OriginalArrivalTime
X-MS-Exchange-CrossTenant-OriginalAttributedTenantConnectingIp
X-MS-Exchange-CrossTenant-rms-persistedconsumerorg
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg
X-MS-Exchange-CrossTenant-userprincipalname
X-MS-Exchange-CrossTenant-UserPrincipalName
X-MS-Exchange-EOPDirect
X-MS-Exchange-Inbox-Rules-Loop
X-MS-Exchange-Message-Is-Ndr
X-MS-Exchange-MessageSentRepresentingType
X-MS-Exchange-Organization-AuthAs
X-MS-Exchange-Organization-AuthSource
X-MS-Exchange-Organization-ExpirationInterval
X-MS-Exchange-Organization-ExpirationIntervalReason
X-MS-Exchange-Organization-ExpirationStartTime
X-MS-Exchange-Organization-ExpirationStartTimeReason
X-MS-Exchange-Organization-MessageDirectionality
X-MS-Exchange-Organization-Network-Message-Id
X-MS-Exchange-Organization-PCL
X-MS-Exchange-Organization-SCL
X-MS-Exchange-Processed-By-BccFoldering
X-MS-Exchange-SenderADCheck
X-MS-Exchange-Transport-CrossTenantHeadersPromoted
X-MS-Exchange-Transport-CrossTenantHeadersStamped
X-MS-Exchange-Transport-CrossTenantHeadersStripped
X-MS-Exchange-Transport-EndToEndLatency
X-MS-Has-Attach
X-MS-Office365-Filtering-Correlation-Id
X-MS-Office365-Filtering-Correlation-Id-Prvs
X-MS-PublicTrafficType
X-MS-TNEF-Correlator
X-MS-TrafficTypeDiagnostic
X-MS-UserLastLogonTime
X-MSFBL
X-Msg-EID
X-msgtype
X-MSMail-Priority
X-MSYS-API
X-Netcore-MailScanner
X-Netcore-MailScanner-ID
X-Netcore-MailScanner-Information
X-Newsletter-Email-Id
X-Notifications
X-Notifications-Bounce-Info
X-Orig-message-ID
X-Original-To
X-OriginalArrivalTime
X-Originating-Ip
X-Originating-IP
X-OriginatorOrg
X-Outgoing
X-P360-DR-ID
X-P360-I-ID
X-P360-P-ID
X-Personalized-By
X-PHP-Originating-Script
X-PHP-Script
X-phpList-version
X-Postfix-Queue-ID
X-Postfix-Sender
X-Postmaster-Msgtype
X-PPP-Message-ID
X-PPP-Vhost
X-Priority
X-ProcessInfo
X-Proofpoint-GUID
X-Proofpoint-ORIG-GUID
X-Proofpoint-Virus-Version
X-Public-IP
X-PVIQ
X-Received
X-Receiver
X-Recruiting
X-Report-Abuse
X-Report-Abuse-To
X-REPORT-ABUSE-TO
X-Return-Path
X-Return-Path-Hint
X-rext
X-RM-Clr
X-RM-EmailName
X-RM-SenderScore
X-RM-SendId
X-Roving-Campaignid
X-Roving-Id
X-rpcampaign
X-RPCampaign
X-RPTags
X-Sable-ID
X-schedule
X-SENDCLOUD-LOG
X-SENDCLOUD-LOG-NEW
X-SENDCLOUD-UUID
X-Sender
X-Sender-Id
X-Sender-IP
X-Senderinfo
X-Sent-Time
X-SES-Outgoing
X-SFDC-App
X-SFDC-Binding
X-SFDC-EmailCategory
X-SFDC-EntityId
X-SFDC-Interface
X-SFDC-LK
X-SFDC-TLS-NoRelay
X-SFDC-User
X-SFMC-Stack
X-SG-EID
X-SG-ID
X-sgxh1
X-sib-id
X-SID-PRA
X-SID-Result
X-SMTP41-MailScanner
X-SMTP41-MailScanner-From
X-SMTP41-MailScanner-ID
X-SMTP41-MailScanner-Information
X-SMTPAPI
X-SONIC-DKIM-SIGN
X-Sonic-MF
X-Source
X-Source-Args
X-Source-Dir
X-Sp-Message-ID
X-Spam-Bar
X-Spam-Flag
X-Spam-Level
X-Spam-Score
X-Spam-Status
X-SubAccount-ID
X-SUBMAIL-send-cmd
X-SUBMAIL-type
X-Subscriber-Uid
X-Test-Mailing
X-TMN
X-Tracking-Did
X-TSO-Forward
X-Virtual-MTA
X-VirtualServerGroup
X-Virus-Scanned
X-Virus-Status
X-VMTA
X-vrfbldomain
X-vrpod
X-vrrpmm
X-WDP-App-Pool
X-WDP-Computer-Name
X-WDP-Connection-ID
X-WDP-Process-ID
X-WDP-Process-Name
X-WDP-Process-Owner
X-WES-AID
X-X-Campaign-Id
X-X-Contact-Id
X-X-Groups
X-X-SendPost-Mock-Email
X-X-SendPost-Mock-Time-Shift
X-X-Team-Id
X-X-Validate
X-Yahoo-Forwarded
X-YahooFilteredBulk
X-YMail-OSG
X-YMailAVSC
X-YMailISG
X-Zoho-RID

**Comment by adamhotep** [comment]
It's dangerous to allow skipping spaces and line breaks just to hit a corner case.

Any RFC 822 (now [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322)) .eml file that has passed through a mail relay should start with a `Return-Path` header (a [trace field](https://www.rfc-editor.org/rfc/rfc5322#section-3.6.7)). This entry matches `Return-Path: <`:
```
    "1:0:52657475726e2d506174683a203c:Mail:CL_TYPE_ANY:CL_TYPE_MAIL", 
```

The rest, as @Sanesecurity pointed out, is a _very_ long list (though the massive paste above doesn't include any of the numerous header names that _don't_ start with `X-`). If you wanted to expand beyond the existing `Date: ` and my proposed `Return-Path: <`, here are the items I'd suggest:
* `From: `
* `MIME-Version: `
* `Received: `
* `Subject: `
* `To: `

Also keep in mind that [mbox](https://en.wikipedia.org/wiki/Mbox) files start with `From ` (note the lack of a colon), see [RFC 4155](https://www.rfc-editor.org/rfc/rfc4155). Mbox files are uncompressed archives of .eml files.

**Comment by micahsnyder** [comment]
I think it's worth noting that `filetypes_int.h` is overridden when loading `daily.cvd` with the `daily.ftm` signatures.  

We try to make sure that `daily.ftm` matches `filetypes_int.h`, so any change we agreed to merge here will also have to be added by our Threat Research team to the daily database or else users won't actually see any detection change.

**Review by micahsnyder — CHANGES_REQUESTED** [review]
As per the above, we should either cancel this, or else change it to use the signatures to detect mail files starting with those headers:
- `Return-Path: <`
- Delivered-To: `
- `From: `
- `MIME-Version: `
- `Received: `
- `Subject: `
- `To: `
- `X-Original-To: `

**Comment by micahsnyder** [comment]
Closing due to inactivity post-review.

**Pull request closed without merging**
