### PR TITLE
clamonacc: Added workaround for NULL-pointer usage in clamonacc-ddd thread.

### PR DESCRIPTION
**Pull request by frank-fegert**
The clamonacc-ddd thread (clamonacc/inotif/inotif.c) has currently no
explicit handling for the special inotify kernel events IN_UNMOUNT,
IN_Q_OVERFLOW and IN_IGNORED. It treats the inotify_event structs in
the same way as regular inotify events, although for those special
events the "len" and "name" fields a value of zero respectively NULL.
This can lead to a SIGSEGV of the clamonacc-ddd thread when calling
"strlen(name)" on a NULL value.
This commit adds just a quick'n'dirty workaround for the SIGSEGV and
some logging output. It DOES NOT fix the more overall issue, that a
IN_Q_OVERFLOW inotify event also leads to an out-of-sync situation
between the monitored filesystem/directory and the internal data
structures "ddd_ht" and "wdlt" of clamonacc.

### CODE REVIEW

**Comment by frank-fegert** [comment]
#245

**Comment by frank-fegert** [comment]
Added a workaround for another SIGSEGV source in the clamonacc-ddd thread, which was observed during further analysis.

**Comment by frank-fegert** [comment]
@m-sola Thank you very much for the review! :smile: I ran this through `clang-format-11` which only came up with minor whitespace changes in https://github.com/Cisco-Talos/clamav/pull/386/commits/92beae2fc4aa624e580e9a71699f4519642e496d.
@micahsnyder What would be the appropriate way to move forward with this? Can you please consider this PR for merge? Thanks!

**Comment by micahsnyder** [comment]
> @frank-fegert looks like just one merge-conflict. Can I trouble you to rebase it with the upstream `main` branch and resolve it, and then force-push the update?

Nevermind, I just realized that merging the previous PR's without rebasing and testing broke the build because of an unrelated PR that changed the `logg()` function API. I'll take care of it.

I've created https://github.com/Cisco-Talos/clamav/pull/483 to fix that, and replace this PR.

**Pull request closed without merging**
