### PR TITLE
Fix issue LLVM linking with libclamav_rust test executable

### PR DESCRIPTION
**Pull request by teoberi**
Fix for issue "Clamav 0.105.0 test libclamav_rust failed #569"

### CODE REVIEW

**Comment by micahsnyder** [comment]
Actually, I'm not entirely happy with the location where this is stripped. It is stripped before building a specific test executable, (check_fpu_endian), and just happens to propagate down to the `libclamav_rust` through the `LLVM_LIBS` environment variable. That makes it feel kind of hacky to me, and easy to accidentally break in the future.

It would be better to either do it:
A) just after `LLVM_LIBRARIES` is first defined in `FindLLVM.cmake`, here: https://github.com/Cisco-Talos/clamav/blob/main/cmake/FindLLVM.cmake#L154
or B) to the `LLVM_LIBS` variable just after `LLVM_LIBS` is created, here: https://github.com/Cisco-Talos/clamav/blob/main/unit_tests/CMakeLists.txt#L172

@teoberi would you please give one of these options a try to ensure it also resolves the issue and doesn't break anything else in your environment?

**Comment by teoberi** [comment]
I use Slackware64-current (development tree) on all my servers where it has already been switched to LLVM 14.0.6.
I no longer have any server with LLVM 13.0.1 and the build with LLVM 14.0.6 crashes at `cmake --build . --config Release` before I get to the `ctest`.
So in conclusion for Slackware I am stuck until problems related to building with LLVM 14 is solved.

**Comment by teoberi** [comment]
I tried with LLVM 13 in an Ubuntu 22.04 virtual machine where is libLLVM-13.so (a single file) using solution A: just after LLVM_LIBRARIES is first defined in FindLLVM.cmake and the result is:

> Test project /tmp/clamav-0.105.0/build
>     Start 1: libclamav
> 1/6 Test #1: libclamav ........................   Passed   40.28 sec
>     Start 2: libclamav_rust
> 2/6 Test #2: libclamav_rust ...................   Passed  1377.48 sec
>     Start 3: clamscan
> 3/6 Test #3: clamscan .........................   Passed    8.67 sec
>     Start 4: clamd
> 4/6 Test #4: clamd ............................   Passed   23.80 sec
>     Start 5: freshclam
> 5/6 Test #5: freshclam ........................   Passed    2.51 sec
>     Start 6: sigtool
> 6/6 Test #6: sigtool ..........................   Passed    0.50 sec
> 
> 100% tests passed, 0 tests failed out of 6
> 
> 
> Total Test time (real) = 1453.24 sec

**Comment by micahsnyder** [comment]
Okay understood. I should've realized that based on our conversations in other issues. Okay I'll tweak it myself and test it as best I can.

**Comment by teoberi** [comment]
I tested in a virtual machine with Slackware64-current and LLVM 13 the proposed solutions:
A) just after LLVM_LIBRARIES is first defined in FindLLVM.cmake -> it works

> Test project /usr/local/src/clamav-0.105.0/build
>     Start 1: libclamav
> 1/6 Test #1: libclamav ........................   Passed   42.09 sec
>     Start 2: libclamav_rust
> 2/6 Test #2: libclamav_rust ...................   Passed    0.38 sec
>     Start 3: clamscan
> 3/6 Test #3: clamscan .........................   Passed   10.93 sec
>     Start 4: clamd
> 4/6 Test #4: clamd ............................   Passed   29.23 sec
>     Start 5: freshclam
> 5/6 Test #5: freshclam ........................   Passed    4.18 sec
>     Start 6: sigtool
> 6/6 Test #6: sigtool ..........................   Passed    1.00 sec
> 
> 100% tests passed, 0 tests failed out of 6
> 
> Total Test time (real) =  87.83 sec

B) to the LLVM_LIBS variable just after LLVM_LIBS is created-> it works

> Test project /usr/local/src/clamav-0.105.0/build
>     Start 1: libclamav
> 1/6 Test #1: libclamav ........................   Passed   43.09 sec
>     Start 2: libclamav_rust
> 2/6 Test #2: libclamav_rust ...................   Passed    0.38 sec
>     Start 3: clamscan
> 3/6 Test #3: clamscan .........................   Passed   10.88 sec
>     Start 4: clamd
> 4/6 Test #4: clamd ............................   Passed   28.37 sec
>     Start 5: freshclam
> 5/6 Test #5: freshclam ........................   Passed    4.15 sec
>     Start 6: sigtool
> 6/6 Test #6: sigtool ..........................   Passed    0.97 sec
> 
> 100% tests passed, 0 tests failed out of 6
> 
> Total Test time (real) =  87.85 sec

**Comment by micahsnyder** [comment]
Awesome thanks @teoberi for testing.

**Pull request merged**
