### PR TITLE
Updated llvm runtime to support llvm versions 8, 9, 10, 11, 12

### PR DESCRIPTION
**Pull request by ragusaa**
Modified bytecode JIT code to support llvm versions 8, 9, 10, 11, 12.
Additionally updated FindLLVM.cmake to the current version, found at
https://github.com/ldc-developers/ldc/blob/master/cmake/Modules/FindLLVM.cmake,
as well as making modifications suggested by Micah Snyder to check VERSION_LESS
in CMakeLists.txt to avoid having modifications to FindLLVM.cmake.

### CODE REVIEW

**Comment by micahsnyder** [comment]
There's a warning about this `#define` being redefined.  Do you know if we need the `#define`, what it does?

```

[ 41%] Building CXX object libclamav/CMakeFiles/bytecode_runtime.dir/c++/bytecode2llvm.cpp.o
In file included from /source/libclamav/c++/bytecode2llvm.cpp:107:
/usr/lib/llvm12/include/llvm/Analysis/CFG.h:140:1: warning: multi-line comment [-Wcomment]
  140 | ///  /   \
      | ^
In file included from /usr/lib/llvm12/include/llvm/Transforms/IPO/Attributor.h:107,
                 from /usr/lib/llvm12/include/llvm/LinkAllPasses.h:44,
                 from /source/libclamav/c++/bytecode2llvm.cpp:136:
/usr/lib/llvm12/include/llvm/Analysis/CGSCCPassManager.h:115: warning: "DEBUG_TYPE" redefined
  115 | #define DEBUG_TYPE "cgscc"
      |
/source/libclamav/c++/bytecode2llvm.cpp:24: note: this is the location of the previous definition
   24 | #define DEBUG_TYPE "clamavjit"
      |
/source/libclamav/c++/bytecode2llvm.cpp:219:13: warning: inline function 'void {anonymous}::cli_dbgmsg(const char*, ...)' used but never defined
  219 | inline void cli_dbgmsg(const char *str, ...) __attribute__((format(printf, 1, 2)));
      |             ^~~~~~~~~~
[ 41%] Built target bytecode_runtime
```

**Comment by micahsnyder** [comment]
There's a warning about variants of an enum not being handled.  Should we add a default case for unsupported platforms?

```
[ 41%] Building CXX object libclamav/CMakeFiles/bytecode_runtime.dir/c++/detect.cpp.o
/source/libclamav/c++/detect.cpp: In function 'void cli_detect_env_jit(cli_environment*)':
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'Ananas' not handled in switch [-Wswitc
]
  131 |     switch (os) {
      |            ^
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'CloudABI' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'Fuchsia' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'IOS' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'KFreeBSD' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'MacOSX' not handled in switch [-Wswitc
]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'ZOS' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'RTEMS' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'NaCl' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'AIX' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'CUDA' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'NVCL' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'AMDHSA' not handled in switch [-Wswitc
]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'PS4' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'ELFIAMCU' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'TvOS' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'WatchOS' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'Mesa3D' not handled in switch [-Wswitc
]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'Contiki' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'AMDPAL' not handled in switch [-Wswitc
]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'HermitCore' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'Hurd' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'WASI' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'Emscripten' not handled in switch [-Wswitch]
/source/libclamav/c++/detect.cpp:131:12: warning: enumeration value 'LastOSType' not handled in switch [-Wswitch]
```

**Comment by micahsnyder** [comment]
[PR-366-possible-fixes.txt](https://github.com/Cisco-Talos/clamav/files/7899798/PR-366-possible-fixes.txt)

I have some changes to try to link the new rust unit test program with llvm, plus a couple other small changes to:
- increase the check_clamav test timeout.
- fix valgrind suppression rule that triggers when testing in `Release` mode.
- stop explicitly linking with libtinfo, because that was for llvm 3.5 support which we no longer need. 

Even with this change I'm running into runtime issues on alpine with the libclamav_rust unit test, and i'm seeing a valgrind test timeout issue on ubuntu with the libclamav_valgrind test.  More investigation needed.

**Comment by micahsnyder** [comment]
Just rebased the PR to resolve conflicts and get it to run the tests.

Locally I noticed that the clamscan_valgrind test picked up a "possible" leak of of the JIT watchdog thread:
```

5: [INFO]: ==19177== 304 bytes in 1 blocks are possibly lost in loss record 53 of 57
5: [INFO]: ==19177==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
5: [INFO]: ==19177==    by 0x40149CA: allocate_dtv (dl-tls.c:286)
5: [INFO]: ==19177==    by 0x40149CA: _dl_allocate_tls (dl-tls.c:532)
5: [INFO]: ==19177==    by 0x7505322: allocate_stack (allocatestack.c:622)
5: [INFO]: ==19177==    by 0x7505322: pthread_create@@GLIBC_2.2.5 (pthread_create.c:660)
5: [INFO]: ==19177==    by 0x50E4FB5: watchdog_arm(watchdog_item*, int, unsigned char volatile*) (bytecode2llvm.cpp:2059)
5: [INFO]: ==19177==    by 0x50E52BB: cli_vm_execute_jit (bytecode2llvm.cpp:2117)
5: [INFO]: ==19177==    by 0x4F3ED7B: cli_bytecode_run (bytecode.c:1868)
5: [INFO]: ==19177==    by 0x4F43992: cli_bytecode_runhook (bytecode.c:2877)
5: [INFO]: ==19177==    by 0x4FDCE82: run_pdf_hooks (pdf.c:1075)
5: [INFO]: ==19177==    by 0x4FE3F5D: cli_pdf (pdf.c:3656)
5: [INFO]: ==19177==    by 0x4EFBFCC: cli_scanpdf (scanners.c:2912)
5: [INFO]: ==19177==    by 0x4F01601: cli_magic_scan (scanners.c:4801)
5: [INFO]: ==19177==    by 0x4F029CB: scan_common (scanners.c:5317)
```

I don't think it's a real leak, and I'm not worried.  We'll be disabling "possibly lost" valgrind alerts in the near future (for the image fuzzy hash PR) so it's not worth adding a suppression.

**Comment by micahsnyder** [comment]
@ragusaa I'm thinking now we should possibly add something to `INSTALL.md` to suggest that the CMake options `CMAKE_FIND_PACKAGE_PREFER_CONFIG`, `CMAKE_PREFIX_PATH`, and `CMAKE_MODULE_PATH`, may help with detecting all of the required LLVM libraries when installed to a custom location. For example:
```
        -D CMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE \
        -D CMAKE_PREFIX_PATH="$HOME/.mussels/install/host-static" \
        -D CMAKE_MODULE_PATH="$HOME/.mussels/install/host-static/lib/cmake" \
```

**Comment by ragusaa** [comment]
> There's a warning about this `#define` being redefined. Do you know if we need the `#define`, what it does?
> 
> ```
> 
> [ 41%] Building CXX object libclamav/CMakeFiles/bytecode_runtime.dir/c++/bytecode2llvm.cpp.o
> In file included from /source/libclamav/c++/bytecode2llvm.cpp:107:
> /usr/lib/llvm12/include/llvm/Analysis/CFG.h:140:1: warning: multi-line comment [-Wcomment]
>   140 | ///  /   \
>       | ^
> In file included from /usr/lib/llvm12/include/llvm/Transforms/IPO/Attributor.h:107,
>                  from /usr/lib/llvm12/include/llvm/LinkAllPasses.h:44,
>                  from /source/libclamav/c++/bytecode2llvm.cpp:136:
> /usr/lib/llvm12/include/llvm/Analysis/CGSCCPassManager.h:115: warning: "DEBUG_TYPE" redefined
>   115 | #define DEBUG_TYPE "cgscc"
>       |
> /source/libclamav/c++/bytecode2llvm.cpp:24: note: this is the location of the previous definition
>    24 | #define DEBUG_TYPE "clamavjit"
>       |
> /source/libclamav/c++/bytecode2llvm.cpp:219:13: warning: inline function 'void {anonymous}::cli_dbgmsg(const char*, ...)' used but never defined
>   219 | inline void cli_dbgmsg(const char *str, ...) __attribute__((format(printf, 1, 2)));
>       |             ^~~~~~~~~~
> [ 41%] Built target bytecode_runtime
> ```

I searched, and this only appears to be used in LLVM_DEBUG, STATISTIC, and ALWAYS_ENABLED_STATISTIC.  We don't use any of those, so I removed it.

**Comment by micahsnyder** [comment]
After adding that last commit removing the shim for llvm versions < 3.0, I ran this through the test pipelines and did some basic manual testing on Linux.  Outside of a null-deref bug already introduced in `main` that we need to fix before the final release, the test results seemed promising.

Some comments about LLVM runtime support:
- Debug builds appear to crash on some asserts when building constants for bytecode globals. Release builds seem okay. 
- I have had mixed results trying to use LLVM package distributions:
  - Not all distributions have packages for LLVM 8 or newer. 
  - Some distro packages are missing libPolly.a, observed on Debian, Ubuntu, and OpenSUSE.
- Outside of the libPolly.a issue, I've had good luck using `-D CMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE` for LLVM detection on Linux.  If not using this option, my linux builds failed with linker issues that appear to be because LLVM was build without RTTI support and the `bytecode_runtime` object in ClamAV is built _with_ RTTI support (apparently you can't mix the two?).  Disabling RTTI support in our build appears to solve that problem, but then other issues crop up during the tests which I didn't understand.  So I think we have more work to do with the `FindLLVM.cmake` file to make it work well on all supported platforms.  `CMAKE_FIND_PACKAGE_PREFER_CONFIG` doesn't appear to be required on Windows. 

Overall I think PR makes solid progress, though we have more to do before we can recommend LLVM JIT for the runtime over the bytecode interpreter.

**Review by micahsnyder — APPROVED** [review]

**Pull request merged**
