### PR TITLE
remove duplicate #include. fix typos.

### PR DESCRIPTION
**Pull request by RainRat**

### CODE REVIEW

**Review by micahsnyder — APPROVED** [review]
Thanks @RainRat looks good.

**Comment by micahsnyder** [comment]
@RainRat Oh just saw there are conflicts.  Can you rebase with the upstream main branch to resolve them?

**Comment by RainRat** [comment]
Oh no, I think I did the reverse.

**Comment by RainRat** [comment]
Ok, I think it's good now

**Review by micahsnyder — APPROVED** [review]

**Comment by micahsnyder** [comment]
Thanks @RainRat

**Pull request merged**
